# Use the official PHP Apache image as the base image
FROM php:7.4-apache

# Set the working directory
WORKDIR /var/www/html

# Database credentials
ENV DB_HOST=localhost \
    DB_NAME=test \
    DB_USERNAME=root \
    DB_PASSWORD=

# Install PDO extension for MySQL
RUN docker-php-ext-install pdo pdo_mysql

# Expose port 80
EXPOSE 80
